/**
 * The shared secret a site install presents to the central server, in a form
 * a person can actually handle: generated by the product (never
 * `openssl rand -hex 32` by hand), grouped for reading, and checksummed so a
 * typo, a truncated paste, or a Persian-digit paste is rejected at the input
 * instead of surfacing as a silent 401 at the next push.
 *
 * Framework-free and isomorphic on purpose — the sync settings tab is a
 * client component and validates a pasted value with `parseSyncToken` before
 * the save round-trip, so this file must bundle for the browser. That rules
 * out `node:crypto`; randomness comes from Web Crypto (present in browsers
 * and in Node 18+ as `globalThis.crypto`) and the alphabet comes from
 * code-alphabet.ts rather than pairing-codes.ts, which does import
 * `node:crypto`.
 *
 * Canonical form: POS1-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-CC
 *                 ^prefix ^--------- 32 chars of entropy --------- ^checksum
 */
import { PAIRING_CODE_ALPHABET, foldDigits } from "./code-alphabet";

/**
 * Version marker. A future format change gets a new prefix, so an old token
 * is *detectably* old (`bad_prefix`) rather than silently mis-parsed.
 */
export const SYNC_TOKEN_PREFIX = "POS1";

/** 32 symbols from a 32-symbol alphabet — 160 bits. */
const PAYLOAD_LENGTH = 32;
const CHECKSUM_LENGTH = 2;
const GROUP_LENGTH = 4;

export type SyncTokenError = "bad_prefix" | "bad_length" | "bad_charset" | "bad_checksum";

export type ParseSyncTokenResult =
  | { ok: true; canonical: string }
  | { ok: false; error: SyncTokenError };

/**
 * Two checksum characters over the payload, as a positional weighted sum mod
 * 32² so both characters carry information. 31 is odd and therefore
 * invertible mod 1024, which makes every single-character substitution and
 * every adjacent transposition detectable — the two mistakes someone
 * re-typing a token actually makes.
 */
function checksumOf(payload: string): string {
  let sum = 0;
  for (const ch of payload) {
    sum = (sum * 31 + PAIRING_CODE_ALPHABET.indexOf(ch)) % 1024;
  }
  return PAIRING_CODE_ALPHABET[(sum >> 5) & 31] + PAIRING_CODE_ALPHABET[sum & 31];
}

/** Groups the body into 4-character runs and prefixes it: the display form. */
function toCanonical(payload: string, checksum: string): string {
  const groups: string[] = [SYNC_TOKEN_PREFIX];
  for (let i = 0; i < payload.length; i += GROUP_LENGTH) {
    groups.push(payload.slice(i, i + GROUP_LENGTH));
  }
  groups.push(checksum);
  return groups.join("-");
}

/**
 * A fresh token in canonical display form.
 *
 * The alphabet is exactly 32 symbols, so `byte & 31` is a uniform index with
 * no modulo bias and no rejection sampling needed.
 */
export function generateSyncToken(): string {
  const bytes = new Uint8Array(PAYLOAD_LENGTH);
  globalThis.crypto.getRandomValues(bytes);
  let payload = "";
  for (const byte of bytes) payload += PAIRING_CODE_ALPHABET[byte & 31];
  return toCanonical(payload, checksumOf(payload));
}

/**
 * Anything a person might paste -> the bare characters.
 *
 * Folds Persian/Arabic-Indic digits (reusing the folding normalizePairingCode
 * does), uppercases, and drops hyphens, spaces, and any other separator. Note
 * it does *not* fold 0→O / 1→I the way normalizePairingCode does: the prefix
 * `POS1` contains a literal `1`, so that pass would corrupt it. A `0` or `1`
 * inside the body is reported as `bad_charset` instead, which is the honest
 * answer — those characters are never issued.
 */
export function normalizeSyncToken(raw: string): string {
  return foldDigits(raw).toUpperCase().replace(/[^A-Z0-9]/g, "");
}

/**
 * Validates a token and returns it in canonical display form, so both sides
 * store — and therefore hash — the same bytes regardless of how it was typed.
 */
export function parseSyncToken(raw: string): ParseSyncTokenResult {
  const normalized = normalizeSyncToken(raw);
  if (!normalized.startsWith(SYNC_TOKEN_PREFIX)) return { ok: false, error: "bad_prefix" };

  const body = normalized.slice(SYNC_TOKEN_PREFIX.length);
  if (body.length !== PAYLOAD_LENGTH + CHECKSUM_LENGTH) return { ok: false, error: "bad_length" };
  if ([...body].some((ch) => !PAIRING_CODE_ALPHABET.includes(ch))) return { ok: false, error: "bad_charset" };

  const payload = body.slice(0, PAYLOAD_LENGTH);
  const checksum = body.slice(PAYLOAD_LENGTH);
  if (checksumOf(payload) !== checksum) return { ok: false, error: "bad_checksum" };

  return { ok: true, canonical: toCanonical(payload, checksum) };
}

/**
 * The 64-character hex secrets minted before this format existed
 * (`randomBytes(32).toString("hex")`, and the `openssl rand -hex 32` the UI
 * used to tell owners to run). Every already-paired laptop holds one, so they
 * stay valid — rejecting them outright would break every existing install on
 * upgrade. The UI flags them as legacy so they get rotated in due course.
 */
export function isLegacySyncToken(raw: string): boolean {
  return /^[0-9a-f]{32,}$/i.test(raw.trim());
}
