// Compiles the app's Tailwind v4 stylesheet (src/app/globals.css) into a static
// CSS file containing every utility the components use plus the design tokens
// (:root / .dark custom properties). The design-sync converter needs a real
// stylesheet for cssEntry — the raw globals.css only holds `@import "tailwindcss"`
// and @theme token definitions, so shipping it verbatim would leave every
// component unstyled. Auto content-detection scans the repo, so all utilities
// used anywhere in src/ (which includes src/components/ui) are emitted.
//
// Output: .design-sync/.cache/compiled.css (gitignored, regenerated by buildCmd).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const input = resolve(repoRoot, 'src/app/globals.css');
const outDir = resolve(repoRoot, '.design-sync/.cache');
const out = resolve(outDir, 'compiled.css');

const css = readFileSync(input, 'utf8');
const result = await postcss([tailwind()]).process(css, { from: input, to: out });

// The app loads Vazirmatn (the Persian brand font) via next/font/local at
// runtime, exposing it as --font-vazirmatn. That runtime mechanism isn't
// present in the DS bundle, so ship the font self-contained: an @font-face with
// the woff2 inlined as a data-URI, and a concrete value for --font-vazirmatn so
// the `var(--font-vazirmatn), "Vazirmatn", …` stack in the tokens resolves.
const woff2 = readFileSync(resolve(repoRoot, 'src/app/fonts/Vazirmatn-Variable.woff2'));
const dataUri = `data:font/woff2;base64,${woff2.toString('base64')}`;
const fontBlock = `
/* Vazirmatn brand font — inlined so the bundle is self-contained (app serves it via next/font at runtime). */
@font-face {
  font-family: "Vazirmatn";
  src: url(${dataUri}) format("woff2");
  font-weight: 100 900;
  font-display: swap;
  font-style: normal;
}
:root { --font-vazirmatn: "Vazirmatn"; }
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(out, result.css + '\n' + fontBlock);
console.error(`compiled ${input} -> ${out} (${((result.css.length + fontBlock.length) / 1024).toFixed(1)} KiB, font inlined)`);
