-- ============================================================================
-- 0194_aec_profiles_and_participants.sql — issue #799 Wave 2.
--
-- The AEC vertical's three new tables. Everything else this wave needs already
-- exists: `ai_projects` is the project (0167 gave it customer, dates, type,
-- tags, phases, tasks, members, contracts, documents, approvals and events),
-- `parties` is the identity of every company and person, `users` +
-- `workspace_members` are the internal team and its roles, and `media_assets`
-- is the file store. This migration adds only what is genuinely AEC-shaped and
-- cannot be derived:
--
--   1. `aec_business_profiles` — the operating profile a business picked
--      (architecture office, contractor, individual, …), its specialties and
--      its explicit capability overrides. Business-scoped, one row per tenant.
--   2. `aec_project_profiles` — the AEC extension of ONE project: its number,
--      site and areas, the employer/consultant/contractor parties, the contract
--      and delivery method, permit references, planned vs actual dates and
--      planned vs reported physical progress. A 1:1 extension, not a second
--      project table.
--   3. `aec_project_participants` — who is who on the project: an external
--      party plus a professional role. Additive to `workspace_members`, which
--      stays the ONLY source of internal authorization.
--
-- Three rules this file follows, from the repo's standing conventions and the
-- issue's §32:
--
--   * EVERY TABLE IS RLS-ENABLED, FORCED, with the standard `tenant_isolation`
--     policy. There is no exempt case here: all three carry `business_id`.
--   * TENANT INTEGRITY IS STRUCTURAL, NOT HOPED FOR. A project profile cannot
--     point at another tenant's project at all — the foreign key is the
--     composite `(business_id, project_id)` — and a party or user reference is
--     validated by a trigger that refuses a row whose party belongs to a
--     different business (see the note on why a composite FK cannot carry
--     ON DELETE SET NULL).
--   * NOTHING IS BACKFILLED and nothing existing is altered beyond adding the
--     two UNIQUE constraints the composite foreign keys need. An upgrading
--     tenant gets three empty tables; an F&B tenant never reads them.
--
-- Wave 2 deliberately does NOT classify these tables for hybrid/offline sync:
-- they are cloud-only for now, and §26's sync classification lands with the
-- site-execution wave. `aec.integration.test.ts` asserts they are not captured
-- by the master feed, so "not synced" is a stated fact rather than an oversight.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. The two UNIQUE constraints the composite foreign keys need.
-- ---------------------------------------------------------------------------
-- A composite FK requires a unique constraint on the referenced columns. Both
-- are cheap (`id` is already the primary key) and both are strictly additive.
-- `users` already carries one from migration 0187 (`users_business_id_id_iam_unique`),
-- so only projects and parties are added here.
ALTER TABLE ai_projects ADD CONSTRAINT ai_projects_business_id_id_unique UNIQUE (business_id, id);

-- `parties` is referenced by three columns below. The unique constraint is what
-- makes "this party belongs to this business" a fact the database enforces
-- rather than a promise the service layer makes.
ALTER TABLE parties ADD CONSTRAINT parties_business_id_id_unique UNIQUE (business_id, id);

-- ---------------------------------------------------------------------------
-- 1. The business's operating profile
-- ---------------------------------------------------------------------------
-- One row per AEC business. A business of any other industry never gets one,
-- and the service refuses to write one for a tenant whose `businesses.industry`
-- is not `architecture_construction` (aec-service.ts) — so "an F&B tenant
-- cannot acquire AEC configuration" holds even if a route were mis-wired.
--
-- `operating_profile` is text + CHECK rather than an enum, the same choice
-- `businesses.industry` made: the catalogue lives in code (`src/lib/aec.ts`) so
-- a new profile ships with the app, and the CHECK is regenerated by the next
-- migration exactly as the industry constraint is.
--
-- The default is `architecture_office` — the leanest shape that still has a
-- design register — matching `AEC_DEFAULT_OPERATING_PROFILE`. A column default
-- rather than "null means default" so the row is always self-describing.
CREATE TABLE aec_business_profiles (
    business_id          uuid PRIMARY KEY REFERENCES businesses(id) ON DELETE CASCADE,
    operating_profile    text NOT NULL DEFAULT 'architecture_office'
        CHECK (operating_profile IN (
            'architecture_office',
            'civil_engineering',
            'contractor',
            'design_build',
            'consulting_supervision',
            'multidisciplinary',
            'team',
            'individual'
        )),
    -- The disciplines the business tags itself with (architecture, MEP,
    -- surveying, …). Labels, never a gate: nothing in the product hides behind
    -- a specialty, so an unknown value is dropped by the service rather than
    -- rejected here. The CHECK keeps the column honest for the values this
    -- release knows, and is widened by the migration that adds a discipline.
    specialties          text[] NOT NULL DEFAULT '{}'
        CHECK (specialties <@ ARRAY[
            'architecture',
            'structural_engineering',
            'civil_engineering',
            'interior_architecture',
            'landscape',
            'mep',
            'surveying',
            'project_management',
            'construction_management',
            'site_supervision',
            'quantity_surveying'
        ]::text[]),
    -- Explicit capability deltas only — a capability whose value equals the
    -- profile's own preset is not stored (`normalizeAecCapabilityOverrides`),
    -- so this column stays small and a future change to a preset is not frozen
    -- out by a tenant that never meant to override it.
    capability_overrides jsonb NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(capability_overrides) = 'object'),
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE aec_business_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE aec_business_profiles FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON aec_business_profiles FOR ALL
    USING (app_rls_bypass() OR business_id = app_current_business())
    WITH CHECK (app_rls_bypass() OR business_id = app_current_business());

-- ---------------------------------------------------------------------------
-- 2. The project's AEC profile
-- ---------------------------------------------------------------------------
-- One row per AEC project, created lazily the first time somebody fills the
-- form in. Nothing is required except the project itself: an existing project
-- gains no obligation from this table's existence, which is what lets Wave 3's
-- cockpit show "این پروژه هنوز پروفایل پیمانکاری ندارد" instead of failing.
--
-- Why `(business_id, project_id)` and not a bare `project_id`: with the
-- composite key, a cross-tenant project reference is not merely rejected by a
-- service check — it cannot be inserted, by anyone, with any SQL. And because
-- the row is business-scoped, its RLS policy is the same one-line policy as
-- every other direct tenant table rather than a parent-scoped subquery.
--
-- The three party columns are single-column FKs on purpose, and this is the one
-- place the obvious constraint would have been wrong: a composite FK can only
-- carry `ON DELETE SET NULL` if *every* column in it is nullable, and
-- `business_id` is NOT NULL. So a party reference is a plain
-- `REFERENCES parties(id) ON DELETE SET NULL` (deleting a party must never
-- delete the project's record of who it was for), and tenancy is enforced
-- instead by `aec_assert_references_are_tenant_owned()` below — a trigger that
-- refuses a party or user from another business at write time. The trade is
-- deliberate and the trigger is stricter than the FK would have been: it also
-- catches a party from *the same business's* other branch or an inactive user,
-- which no foreign key could express.
--
-- Names, not copies: the employer's phone number lives on the party, and the
-- project shows it by joining. `parties` remains the one identity table, which
-- is what keeps a merge from having to rewrite a second copy of a company name.
CREATE TABLE aec_project_profiles (
    id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id                 uuid NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    project_id                  uuid NOT NULL,
    -- The contract's own number («قرارداد ۱۴۰۳/۱۲»), distinct from the id and
    -- free text because every office has its own convention.
    project_number              text,
    project_category            text,
    site_name                   text,
    address                     text,
    city                        text,
    region                      text,
    -- Geo coordinates "when useful" (§5). Numeric, not float: a coordinate is
    -- a fixed-precision fact, and the dashboard will cluster on it.
    latitude                    numeric(9, 6) CHECK (latitude IS NULL OR (latitude >= -90 AND latitude <= 90)),
    longitude                   numeric(9, 6) CHECK (longitude IS NULL OR (longitude >= -180 AND longitude <= 180)),
    -- Square metres / count, as numeric(14, 2): plot areas are routinely
    -- fractional and a 12-digit thousands separator should never appear.
    land_area                   numeric(14, 2) CHECK (land_area IS NULL OR land_area >= 0),
    built_area                  numeric(14, 2) CHECK (built_area IS NULL OR built_area >= 0),
    floor_count                 integer CHECK (floor_count IS NULL OR (floor_count >= 0 AND floor_count <= 500)),
    -- Who the parties are. `ai_projects.party_id` remains the project's client
    -- in the generic model; these name the AEC roles explicitly, because a
    -- contractor project's "client" and its "employer" are the same company
    -- while its lead consultant and main contractor are two others.
    employer_party_id           uuid REFERENCES parties(id) ON DELETE SET NULL,
    lead_consultant_party_id    uuid REFERENCES parties(id) ON DELETE SET NULL,
    main_contractor_party_id    uuid REFERENCES parties(id) ON DELETE SET NULL,
    -- The internal project manager: a platform user, never a party. §6 keeps
    -- professional titles off the authorization model, so this is a *pointer*
    -- for display and assignment — it grants nothing.
    project_manager_user_id     uuid REFERENCES users(id) ON DELETE SET NULL,
    contract_method             text,
    delivery_method             text,
    -- Permit and reference numbers are a list: a project has a building permit,
    -- a municipal reference and often a separate electrical one.
    permit_numbers              text[] NOT NULL DEFAULT '{}',
    planned_start_date          date,
    planned_end_date            date,
    actual_start_date           date,
    actual_end_date             date,
    -- Physical progress in percent. Two columns, never one: "what the plan
    -- says" and "what the site reported" are different numbers and the gap
    -- between them is the report (§30's schedule variance).
    planned_physical_progress   numeric(5, 2)
        CHECK (planned_physical_progress IS NULL OR (planned_physical_progress >= 0 AND planned_physical_progress <= 100)),
    reported_physical_progress  numeric(5, 2)
        CHECK (reported_physical_progress IS NULL OR (reported_physical_progress >= 0 AND reported_physical_progress <= 100)),
    notes                       text NOT NULL DEFAULT '',
    created_at                  timestamptz NOT NULL DEFAULT now(),
    updated_at                  timestamptz NOT NULL DEFAULT now(),
    -- One profile per project, and the project must be this business's.
    UNIQUE (project_id),
    FOREIGN KEY (business_id, project_id)
        REFERENCES ai_projects (business_id, id) ON DELETE CASCADE,
    CHECK (planned_start_date IS NULL OR planned_end_date IS NULL OR planned_end_date >= planned_start_date),
    CHECK (actual_start_date IS NULL OR actual_end_date IS NULL OR actual_end_date >= actual_start_date)
);
CREATE INDEX idx_aec_project_profiles_business
    ON aec_project_profiles (business_id);
CREATE INDEX idx_aec_project_profiles_employer
    ON aec_project_profiles (employer_party_id) WHERE employer_party_id IS NOT NULL;
CREATE INDEX idx_aec_project_profiles_consultant
    ON aec_project_profiles (lead_consultant_party_id) WHERE lead_consultant_party_id IS NOT NULL;
CREATE INDEX idx_aec_project_profiles_contractor
    ON aec_project_profiles (main_contractor_party_id) WHERE main_contractor_party_id IS NOT NULL;
CREATE INDEX idx_aec_project_profiles_planned_end
    ON aec_project_profiles (business_id, planned_end_date) WHERE planned_end_date IS NOT NULL;

ALTER TABLE aec_project_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE aec_project_profiles FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON aec_project_profiles FOR ALL
    USING (app_rls_bypass() OR business_id = app_current_business())
    WITH CHECK (app_rls_bypass() OR business_id = app_current_business());

-- ---------------------------------------------------------------------------
-- 3. Who is who on the project
-- ---------------------------------------------------------------------------
-- §6: "Add external project participant/assignment support based on existing
-- `parties`." One row = one party in one professional role on one project. A
-- company that is both the architect and the supervision consultant has two
-- rows, and that is intentional: the roles are what the cockpit groups by, and
-- a single "role" column could not express it.
--
-- WHAT THIS TABLE IS NOT: a grant. Attaching a party here creates no user, no
-- session and no membership — `workspace_members` remains the only table that
-- answers "what may this person do", and `aec.integration.test.ts` asserts that
-- recording a participant leaves `users` and `workspace_members` untouched.
--
-- The role list is the issue's §6 list verbatim. A role whose capability is off
-- for the business's operating profile is refused by the service (`aec.ts`'s
-- `aecParticipantRoleAllowed`) — so an individual architect cannot record a
-- subcontractor without switching the capability on. The CHECK is the outer
-- bound; the service applies the profile.
CREATE TABLE aec_project_participants (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id  uuid NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    project_id   uuid NOT NULL,
    party_id     uuid NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
    role         text NOT NULL CHECK (role IN (
        'client', 'employer_representative',
        'architect', 'lead_architect', 'structural_engineer', 'civil_engineer',
        'mep_consultant', 'landscape_consultant', 'project_manager',
        'construction_manager', 'supervision_consultant',
        'contractor', 'subcontractor', 'supplier',
        'quantity_surveyor', 'estimator',
        'site_engineer', 'foreman', 'inspector', 'qa_qc', 'hse', 'surveyor'
    )),
    -- A contact person at that company, free text: the engineer who answers the
    -- phone on site is not necessarily a CRM record, and forcing one would make
    -- the register unusable.
    contact_name text,
    notes        text NOT NULL DEFAULT '',
    -- Engagement window. Optional; a participant with no dates is simply
    -- "involved". `ended_at` is what retires a subcontractor without deleting
    -- the history of them having been on the job.
    started_at   date,
    ended_at     date,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    -- One party holds a given role once per project. The same party may hold
    -- several roles (two rows), and a role may be filled by several parties
    -- (a joint venture contractor), which is exactly what a construction
    -- register needs.
    UNIQUE (project_id, party_id, role),
    FOREIGN KEY (business_id, project_id)
        REFERENCES ai_projects (business_id, id) ON DELETE CASCADE,
    CHECK (started_at IS NULL OR ended_at IS NULL OR ended_at >= started_at)
);
CREATE INDEX idx_aec_project_participants_project
    ON aec_project_participants (project_id, role);
CREATE INDEX idx_aec_project_participants_party
    ON aec_project_participants (party_id);
CREATE INDEX idx_aec_project_participants_business
    ON aec_project_participants (business_id);

ALTER TABLE aec_project_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE aec_project_participants FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON aec_project_participants FOR ALL
    USING (app_rls_bypass() OR business_id = app_current_business())
    WITH CHECK (app_rls_bypass() OR business_id = app_current_business());

-- ---------------------------------------------------------------------------
-- 4. Cross-tenant reference guard
-- ---------------------------------------------------------------------------
-- The composite foreign keys above make a cross-tenant *project* impossible.
-- The party and user references cannot use one (see the note in §2), so this
-- trigger is what makes them equally impossible — and it is deliberately
-- stricter than a foreign key could be, because it also refuses a party that
-- has been archived or merged away and a user who is no longer active. Those
-- are the references the cockpit would otherwise render as a blank cell.
--
-- `SECURITY DEFINER` is not needed and is deliberately absent: the queries run
-- as the caller, and they name `business_id` explicitly, so the answer is the
-- same with or without row-level security — which is what makes the guard
-- trustworthy under both the app role and the migration owner.
CREATE OR REPLACE FUNCTION aec_assert_tenant_owned_references() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    missing text;
BEGIN
    IF NEW.employer_party_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM parties
                        WHERE id = NEW.employer_party_id
                          AND business_id = NEW.business_id
                          AND merged_into_id IS NULL) THEN
        missing := 'employer_party_id';
    END IF;

    IF missing IS NULL AND NEW.lead_consultant_party_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM parties
                        WHERE id = NEW.lead_consultant_party_id
                          AND business_id = NEW.business_id
                          AND merged_into_id IS NULL) THEN
        missing := 'lead_consultant_party_id';
    END IF;

    IF missing IS NULL AND NEW.main_contractor_party_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM parties
                        WHERE id = NEW.main_contractor_party_id
                          AND business_id = NEW.business_id
                          AND merged_into_id IS NULL) THEN
        missing := 'main_contractor_party_id';
    END IF;

    IF missing IS NULL AND NEW.project_manager_user_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM users
                        WHERE id = NEW.project_manager_user_id
                          AND business_id = NEW.business_id) THEN
        missing := 'project_manager_user_id';
    END IF;

    IF missing IS NOT NULL THEN
        RAISE EXCEPTION 'aec_project_profiles.% must reference a record of the same business', missing
            USING ERRCODE = 'foreign_key_violation';
    END IF;

    RETURN NEW;
END $$;

CREATE TRIGGER trg_aec_project_profiles_tenant_refs
    BEFORE INSERT OR UPDATE OF business_id, employer_party_id, lead_consultant_party_id,
        main_contractor_party_id, project_manager_user_id
    ON aec_project_profiles
    FOR EACH ROW EXECUTE FUNCTION aec_assert_tenant_owned_references();

/**
 * The same guard for participants, in its own function because the column names
 * differ and a shared one would need dynamic SQL for no gain.
 *
 * It also refuses a party that is archived or already merged away: those are
 * precisely the records a merge leaves behind, and a participant row pointing
 * at one would be a broken reference the moment it was written.
 */
CREATE OR REPLACE FUNCTION aec_assert_participant_party_tenant_owned() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM parties
                    WHERE id = NEW.party_id
                      AND business_id = NEW.business_id
                      AND merged_into_id IS NULL) THEN
        RAISE EXCEPTION 'aec_project_participants.party_id must reference a live party of the same business'
            USING ERRCODE = 'foreign_key_violation';
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER trg_aec_project_participants_tenant_refs
    BEFORE INSERT OR UPDATE OF business_id, party_id
    ON aec_project_participants
    FOR EACH ROW EXECUTE FUNCTION aec_assert_participant_party_tenant_owned();
