import type { MeterDefinition } from "./types";

/**
 * The one meter catalogue. Feature modules emit these keys; they do not
 * invent prices. Customer-facing prices live in `billing_price_versions`.
 */
export const METER_CATALOGUE: readonly MeterDefinition[] = [
  {
    key: "ai.input_tokens",
    name: "توکن ورودی هوش مصنوعی",
    description: "توکن‌های ورودی یک درخواست تکمیل‌شده.",
    unit: "token",
    aggregation: "sum",
    billingPeriodBehavior: "reset",
    customerVisible: true,
    billable: true,
    active: true,
    source: "platform",
    critical: false,
  },
  {
    key: "ai.output_tokens",
    name: "توکن خروجی هوش مصنوعی",
    description: "توکن‌های خروجی یک درخواست تکمیل‌شده.",
    unit: "token",
    aggregation: "sum",
    billingPeriodBehavior: "reset",
    customerVisible: true,
    billable: true,
    active: true,
    source: "platform",
    critical: false,
  },
  {
    key: "ai.request",
    name: "درخواست هوش مصنوعی",
    description: "یک درخواست تکمیل‌شده به دستیار.",
    unit: "request",
    aggregation: "sum",
    billingPeriodBehavior: "reset",
    customerVisible: true,
    billable: true,
    active: true,
    source: "platform",
    critical: false,
  },
  {
    key: "ai.credit",
    name: "اعتبار هوش مصنوعی",
    description: "اعتبار ریالی مصرف‌شده پس از سهمیهٔ پلن.",
    unit: "rial",
    aggregation: "sum",
    billingPeriodBehavior: "reset",
    customerVisible: true,
    billable: true,
    active: true,
    source: "platform",
    critical: false,
  },
  {
    key: "messaging.sms_segment",
    name: "قطعه پیامک",
    description: "تعداد قطعات UCS-2 یک پیامک ارسالی.",
    unit: "segment",
    aggregation: "sum",
    billingPeriodBehavior: "reset",
    customerVisible: true,
    billable: true,
    active: true,
    source: "platform",
    critical: false,
  },
  {
    key: "messaging.email_send",
    name: "ارسال ایمیل",
    description: "یک ایمیل پذیرفته‌شده توسط سرویس‌دهنده.",
    unit: "send",
    aggregation: "sum",
    billingPeriodBehavior: "reset",
    customerVisible: true,
    billable: true,
    active: true,
    source: "platform",
    critical: false,
  },
  {
    key: "media.storage_byte_hour",
    name: "نگهداری فایل",
    description: "بایت-ساعت فضای ذخیره‌شده. پنجرهٔ اندازه‌گیری روزانه است.",
    unit: "byte_hour",
    aggregation: "byte_time",
    billingPeriodBehavior: "reset",
    customerVisible: true,
    billable: true,
    active: true,
    source: "platform",
    critical: true,
  },
  {
    key: "media.image_enhance",
    name: "بهسازی تصویر",
    description: "یک اجرای بهسازی تصویر محصول.",
    unit: "image",
    aggregation: "sum",
    billingPeriodBehavior: "reset",
    customerVisible: true,
    billable: true,
    active: true,
    source: "provider",
    critical: false,
  },
  {
    key: "cms.bandwidth_bytes",
    name: "ترافیک سایت",
    description: "بایت خروجی تحویل‌داده‌شده به بازدیدکننده.",
    unit: "byte",
    aggregation: "sum",
    billingPeriodBehavior: "reset",
    customerVisible: true,
    billable: true,
    active: true,
    source: "eshobe-cms",
    critical: true,
  },
  {
    key: "cms.origin_transfer_bytes",
    name: "انتقال از مبدأ",
    description: "بایت خوانده‌شده از مبدأ برای ساخت پاسخ.",
    unit: "byte",
    aggregation: "sum",
    billingPeriodBehavior: "reset",
    customerVisible: false,
    billable: true,
    active: true,
    source: "eshobe-cms",
    critical: true,
  },
  {
    key: "cms.api_request",
    name: "درخواست API سایت",
    description: "درخواست‌های API سایت‌ساز در یک ساعت.",
    unit: "request",
    aggregation: "sum",
    billingPeriodBehavior: "reset",
    customerVisible: false,
    billable: true,
    active: true,
    source: "eshobe-cms",
    critical: false,
  },
  {
    key: "cms.storage_byte_hour",
    name: "نگهداری فایل سایت",
    description: "بایت-ساعت فایل‌های سایت.",
    unit: "byte_hour",
    aggregation: "byte_time",
    billingPeriodBehavior: "reset",
    customerVisible: true,
    billable: true,
    active: true,
    source: "eshobe-cms",
    critical: true,
  },
  {
    key: "cms.build_second",
    name: "زمان ساخت سایت",
    description: "ثانیه‌های یک ساخت تکمیل‌شده.",
    unit: "second",
    aggregation: "duration",
    billingPeriodBehavior: "reset",
    customerVisible: false,
    billable: true,
    active: true,
    source: "eshobe-cms",
    critical: false,
  },
  {
    key: "cms.deployment",
    name: "انتشار سایت",
    description: "یک انتشار تکمیل‌شده.",
    unit: "deployment",
    aggregation: "sum",
    billingPeriodBehavior: "reset",
    customerVisible: true,
    billable: true,
    active: true,
    source: "eshobe-cms",
    critical: false,
  },
  {
    key: "backup.storage_byte_day",
    name: "نگهداری نسخهٔ پشتیبان",
    description: "بایت-روز نسخه‌های پشتیبان نگهداری‌شده.",
    unit: "byte_day",
    aggregation: "byte_time",
    billingPeriodBehavior: "high_water",
    customerVisible: true,
    billable: true,
    active: true,
    source: "platform",
    critical: false,
  },
  {
    key: "automation.run",
    name: "اجرای خودکارسازی",
    description: "یک اجرای تکمیل‌شدهٔ خودکارسازی.",
    unit: "run",
    aggregation: "sum",
    billingPeriodBehavior: "reset",
    customerVisible: true,
    billable: true,
    active: true,
    source: "platform",
    critical: false,
  },
] as const;

const BY_KEY = new Map(METER_CATALOGUE.map((meter) => [meter.key, meter]));

export function meterByKey(key: string): MeterDefinition | null {
  return BY_KEY.get(key) ?? null;
}

export function meterKeys(): string[] {
  return METER_CATALOGUE.map((meter) => meter.key);
}
