#!/usr/bin/env tsx
/** Full destructive-restore safety acceptance against a disposable release DB. */
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { Client } from "pg";
import { encryptBackup } from "../src/lib/backup";
import { runPgDump } from "../src/lib/pg-tools";
import {
  cleanupStagedDump,
  restoreDumpFile,
  stageDumpFile,
  targetDatabaseName,
} from "../src/lib/restore-engine";

const databaseUrl = process.env.DATABASE_URL;
const toolsDir = process.env.PG_TOOLS_DIR;
if (!databaseUrl || !toolsDir) throw new Error("DATABASE_URL and PG_TOOLS_DIR are required");
const pgDump = path.join(toolsDir, "bin", process.platform === "win32" ? "pg_dump.exe" : "pg_dump");
const pgRestore = path.join(toolsDir, "bin", process.platform === "win32" ? "pg_restore.exe" : "pg_restore");
const work = await fs.mkdtemp(path.join(os.tmpdir(), "suite-restore-acceptance-"));
const dump = path.join(work, "snapshot.dump");
const corrupt = path.join(work, "corrupt.dump");
const emergencyDir = path.join(work, "emergency");
const reportPath = path.resolve(process.env.PACKAGED_RESTORE_REPORT || "packaged-restore-acceptance.json");

async function sql<T extends Record<string, unknown> = Record<string, unknown>>(text: string, values: unknown[] = []) {
  const client = new Client({ connectionString: databaseUrl });
  await client.connect();
  try { return await client.query<T>(text, values); } finally { await client.end(); }
}
async function marker(): Promise<string> {
  const result = await sql<{ label: string }>("SELECT label FROM restore_acceptance.parent WHERE id=9007199254740993");
  return result.rows[0]?.label ?? "missing";
}
async function expectFailure(operation: () => Promise<unknown>, fragment?: string): Promise<string> {
  try { await operation(); } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (fragment && !message.includes(fragment)) throw new Error(`Expected ${fragment}, got ${message}`);
    return message;
  }
  throw new Error("Expected restore operation to fail");
}

const checks: string[] = [];
try {
  await sql(`
    DROP SCHEMA IF EXISTS restore_acceptance CASCADE;
    CREATE SCHEMA restore_acceptance;
    CREATE TABLE restore_acceptance.parent (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      label text NOT NULL UNIQUE
    );
    CREATE TABLE restore_acceptance.child (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      parent_id bigint NOT NULL REFERENCES restore_acceptance.parent(id),
      note text NOT NULL
    );
    INSERT INTO restore_acceptance.parent(id,label) VALUES(9007199254740993,'نسخهٔ امن – café');
    INSERT INTO restore_acceptance.child(parent_id,note) VALUES(9007199254740993,'رابطهٔ خارجی');
    SELECT setval(pg_get_serial_sequence('restore_acceptance.parent','id'),9007199254740993,true);
  `);
  await runPgDump(dump, databaseUrl, pgDump);
  await sql("UPDATE restore_acceptance.parent SET label='live-original' WHERE id=9007199254740993");

  const bytes = await fs.readFile(dump);
  await fs.writeFile(corrupt, bytes.subarray(0, Math.max(32, Math.floor(bytes.length / 4))));
  await expectFailure(() => restoreDumpFile({ databaseUrl, dumpPath: corrupt, source: "corrupt.dump", apply: false, pgRestore, pgDump }), undefined);
  if (await marker() !== "live-original") throw new Error("corrupt verification changed the live database");
  checks.push("corruption-rejected-before-live-change");

  const encrypted = encryptBackup(bytes, "restore-acceptance-passphrase");
  const staged = await stageDumpFile(encrypted, "restore-acceptance-passphrase", "encrypted.dump.enc");
  try {
    const verified = await restoreDumpFile({ databaseUrl, dumpPath: staged.dumpPath, source: staged.sourceName, apply: false, pgRestore, pgDump });
    if (verified.verified.integrity.encoding !== "UTF8") throw new Error("encrypted staged verification did not report UTF8");
  } finally {
    await cleanupStagedDump(staged.workDir);
  }
  await fs.access(staged.workDir).then(() => { throw new Error("plaintext restore staging directory survived cleanup"); }, () => {});
  if (await marker() !== "live-original") throw new Error("verify-only encrypted restore changed live data");
  checks.push("encrypted-custom-format-and-plaintext-cleanup");

  for (const failureInjection of ["after_original_rename", "after_target_swap", "after_regrant"] as const) {
    await expectFailure(
      () => restoreDumpFile({
        databaseUrl,
        dumpPath: dump,
        source: "snapshot.dump",
        apply: true,
        pgRestore,
        pgDump,
        emergencyDir,
        failureInjection,
      }),
      "restore_apply_rolled_back",
    );
    if (await marker() !== "live-original") throw new Error(`${failureInjection} did not restore the original database`);
    checks.push(`rollback-${failureInjection}`);
  }

  const result = await restoreDumpFile({
    databaseUrl,
    dumpPath: dump,
    source: "snapshot.dump",
    apply: true,
    pgRestore,
    pgDump,
    emergencyDir,
  });
  if (await marker() !== "نسخهٔ امن – café") throw new Error("successful swap did not promote the verified snapshot");
  const integrity = await sql<{ id: string; note: string }>(`
    INSERT INTO restore_acceptance.parent(label) VALUES('بعدی') RETURNING id::text;
  `);
  if (BigInt(integrity.rows[0].id) <= 9007199254740993n) throw new Error("bigint identity sequence was not restored exactly");
  const fk = await sql<{ note: string }>("SELECT note FROM restore_acceptance.child WHERE parent_id=9007199254740993");
  if (fk.rows[0]?.note !== "رابطهٔ خارجی") throw new Error("UTF-8/FK data did not survive restore");
  if (!result.applied?.emergencyBackup) throw new Error("successful apply omitted emergency-backup evidence");
  await fs.access(result.applied.emergencyBackup);
  checks.push("verified-scratch-promoted", "emergency-backup-verified", "utf8-bigint-sequence-foreign-key");

  const emergencyFiles = await fs.readdir(emergencyDir);
  const report = {
    schemaVersion: 1,
    status: "PASS",
    targetDatabase: targetDatabaseName(databaseUrl),
    checks,
    rollbackInjectionPoints: 3,
    emergencyBackupsCreated: emergencyFiles.filter((name) => name.endsWith(".dump")).length,
    integrity: result.applied.integrity,
    generatedAt: new Date().toISOString(),
  };
  await fs.writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`);
  console.log(`Packaged restore acceptance passed (${checks.length} checks).`);
} finally {
  await fs.rm(work, { recursive: true, force: true });
}
