/**
 * The seed data of the in-product knowledge base (migration 0131).
 *
 * `npm run db:seed-knowledge` (seed-knowledge.ts) creates these categories,
 * tags and articles idempotently (upsert by slug), loading every article's
 * body from its sibling markdown file under ./articles/. The content is
 * Persian, covers every member-facing corner of the platform in detail, and
 * deliberately says nothing about the super-admin console (/platform/*) —
 * that realm is documented for operators in docs/, not for members.
 *
 * Everything here is ordinary catalogue content the console can later edit,
 * reorder or unpublish — nothing is special about the seeded rows.
 */

export interface SeedCategory {
  slug: string;
  title: string;
  description: string;
  icon: string;
  tone: string;
  sortOrder: number;
}

export interface SeedTag {
  slug: string;
  label: string;
  description: string;
}

export interface SeedArticle {
  slug: string;
  /** The markdown file under scripts/knowledge-seed/articles/. */
  file: string;
  title: string;
  summary: string;
  category: string; // category slug
  sectionKeys: string[];
  tagSlugs: string[];
  sortOrder: number;
  status: "draft" | "published";
}

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    slug: "getting-started",
    title: "شروع کار",
    icon: "🚀",
    tone: "amber",
    description: "ورود، جادوی راه‌اندازی، روز کاری و شیفت‌ها — هر آنچه برای روز اول لازم است.",
    sortOrder: 10,
  },
  {
    slug: "daily-ops",
    title: "فروش روزانه",
    icon: "🧾",
    tone: "amber",
    description: "صندوق فروش، سفارش‌ها، تسویه، ارسال با پیک و کارکرد بدون اینترنت.",
    sortOrder: 20,
  },
  {
    slug: "front-of-house",
    title: "سالن و سرویس",
    icon: "🍽️",
    tone: "rose",
    description: "نقشهٔ سالن، میزها، صفحهٔ آشپزخانه و رزرو میز.",
    sortOrder: 30,
  },
  {
    slug: "menu-items",
    title: "منو و اقلام",
    icon: "📋",
    tone: "emerald",
    description: "ساخت منو، دسته‌بندی اقلام، مادیفایرها و قیمت‌گذاری.",
    sortOrder: 40,
  },
  {
    slug: "customers-growth",
    title: "مشتریان و رشد",
    icon: "🌱",
    tone: "emerald",
    description: "پروندهٔ مشتری، باشگاه وفاداری، کمپین‌ها، کارت هدیه و پورسانت.",
    sortOrder: 50,
  },
  {
    slug: "inventory-purchase",
    title: "انبار و خرید",
    icon: "📦",
    tone: "sky",
    description: "اقلام انبار، رسپی، خرید، انتقال بین شعبه و شمارش با بارکدخوان.",
    sortOrder: 60,
  },
  {
    slug: "money-reports",
    title: "مالی و گزارش",
    icon: "💰",
    tone: "violet",
    description: "داشبورد، دفتر روزنامه و حسابداری دوبل، گزارش‌ساز، اعتبار و پشتیبان‌گیری.",
    sortOrder: 70,
  },
  {
    slug: "online-integrations",
    title: "وب‌سایت و اتصال‌ها",
    icon: "🌐",
    tone: "sky",
    description: "وب‌سایت و فروشگاه آنلاین، وردپرس و ووکامرس، برنامهٔ دسکتاپ، هلو و API.",
    sortOrder: 80,
  },
  {
    slug: "ai-projects",
    title: "هوش مصنوعی و پروژه‌ها",
    icon: "🤖",
    tone: "violet",
    description: "دستیار هوشمند، همکار هوشمند (کارهای خودکار) و پروژه‌ها.",
    sortOrder: 90,
  },
  {
    slug: "settings-team",
    title: "تنظیمات و تیم",
    icon: "⚙️",
    tone: "",
    description: "برگه‌های تنظیمات، کاربران و دسترسی‌ها، شعبه‌ها، اعلان‌ها و پشتیبانی.",
    sortOrder: 100,
  },
  {
    slug: "retail-industries",
    title: "صنایع فروشگاهی",
    icon: "💎",
    tone: "rose",
    description: "طلا و جواهر، ساعت، اکسسوری، آرایشی و بهداشتی، عمده‌فروشی و صنایع کالایی.",
    sortOrder: 110,
  },
];

export const SEED_TAGS: SeedTag[] = [
  { slug: "quickstart", label: "شروع سریع", description: "برای روز اول راه‌اندازی" },
  { slug: "register", label: "صندوق", description: "فروش و تسویه در صندوق" },
  { slug: "printing", label: "چاپ", description: "چاپگر فاکتور، قبض آشپزخانه و برچسب" },
  { slug: "offline", label: "آفلاین", description: "کارکرد بدون اینترنت و صف آفلاین" },
  { slug: "payments", label: "تسویه", description: "روش‌های پرداخت، انعام و تسویهٔ چندگانه" },
  { slug: "marketing", label: "بازاریابی", description: "وفاداری، کمپین و رشد فروش" },
  { slug: "inventory", label: "موجودی", description: "انبار، رسپی و شمارش" },
  { slug: "reports", label: "گزارش", description: "گزارش‌ها و تحلیل فروش" },
  { slug: "web", label: "وب‌سایت", description: "سایت، فروشگاه آنلاین و ووکامرس" },
  { slug: "ai", label: "هوش مصنوعی", description: "دستیار، همکار هوشمند و خودکارسازی" },
  { slug: "security", label: "امنیت", description: "ورود، نشست‌ها و دسترسی‌ها" },
  { slug: "hardware", label: "سخت‌افزار", description: "چاپگر، کشوی پول و بارکدخوان" },
  { slug: "team", label: "تیم", description: "کاربران، نقش‌ها و شیفت‌ها" },
  { slug: "shifts", label: "شیفت و روز کاری", description: "باز و بسته کردن روز و کشیک" },
];

export const SEED_ARTICLES: SeedArticle[] = [
  // ----------------------------- شروع کار ---------------------------------
  {
    slug: "login-and-security",
    file: "login-and-security.md",
    title: "ورود به سیستم، امنیت و نشست‌ها",
    summary: "راه‌های ورود (ایمیل و رمز، ورود سریع با پین، اثر انگشت)، قفل صفحه و مدیریت نشست‌ها.",
    category: "getting-started",
    sectionKeys: [],
    tagSlugs: ["quickstart", "security"],
    sortOrder: 10,
    status: "published",
  },
  {
    slug: "setup-wizard",
    file: "setup-wizard.md",
    title: "جادوی راه‌اندازی اولیه، قدم‌به‌قدم",
    summary: "از نام کسب‌وکار تا اولین فروش: شعبه، منو، مالیات، روش‌های پرداخت، چاپگر و موجودی اولیه.",
    category: "getting-started",
    sectionKeys: [],
    tagSlugs: ["quickstart"],
    sortOrder: 20,
    status: "published",
  },
  {
    slug: "business-day-shifts",
    file: "business-day-shifts.md",
    title: "روز کاری، شیفت‌ها و تسویهٔ آخر شب",
    summary: "روز کاری چیست، شیفت چگونه باز و بسته می‌شود و تفاوت «بستن روز کاری» با گزارش‌ها.",
    category: "getting-started",
    sectionKeys: ["settings"],
    tagSlugs: ["shifts", "quickstart"],
    sortOrder: 30,
    status: "published",
  },
  {
    slug: "help-center",
    file: "help-center.md",
    title: "مرکز آموزش: جست‌وجو، فهرست و لینک به تیترها",
    summary: "هر چیزی که برای استفاده از همین مرکز آموزش لازم است — جست‌وجو، دسته‌ها، برچسب‌ها و لینک لنگری.",
    category: "getting-started",
    sectionKeys: [],
    tagSlugs: ["quickstart"],
    sortOrder: 40,
    status: "published",
  },
  // ----------------------------- فروش روزانه ------------------------------
  {
    slug: "pos-register",
    file: "pos-register.md",
    title: "راهنمای کامل صندوق فروش",
    summary: "ثبت سفارش، مادیفایر، اتصال مشتری، تخفیف، تسویهٔ چندگانه، چاپ فاکتور و کارکرد آفلاین.",
    category: "daily-ops",
    sectionKeys: ["pos"],
    tagSlugs: ["register", "payments", "printing"],
    sortOrder: 10,
    status: "published",
  },
  {
    slug: "orders-queue",
    file: "orders-queue.md",
    title: "سفارش‌ها: پیگیری، اصلاح و ابطال",
    summary: "صف سفارش‌های باز و تسویه‌شده، جزئیات هر سفارش، اصلاح سفارش بسته‌شده با تأیید مدیر.",
    category: "daily-ops",
    sectionKeys: ["orders"],
    tagSlugs: ["register"],
    sortOrder: 20,
    status: "published",
  },
  {
    slug: "payment-ways",
    file: "payment-ways.md",
    title: "روش‌های پرداخت و تسویهٔ چندگانه",
    summary: "کارت‌خوان، نقدی، اعتباری؛ تقسیم یک فاکتور بین چند روش، انعام و تفاوت تسویه با دفتر حسابداری.",
    category: "daily-ops",
    sectionKeys: ["pos", "orders"],
    tagSlugs: ["payments"],
    sortOrder: 30,
    status: "published",
  },
  {
    slug: "delivery-couriers",
    file: "delivery-couriers.md",
    title: "ارسال سفارش با پیک",
    summary: "تخصیص سفارش ارسالی به پیک، وضعیت‌های تحویل و پیگیری سفارش‌های بیرون‌بر.",
    category: "daily-ops",
    sectionKeys: ["delivery"],
    tagSlugs: ["register"],
    sortOrder: 40,
    status: "published",
  },
  {
    slug: "offline-hardware",
    file: "offline-hardware.md",
    title: "حالت آفلاین، چاپگر و بارکدخوان",
    summary: "وقتی اینترنت قطع است چه می‌شود، صف آفلاین چگونه همگام می‌شود و چاپگر/بارکدخوان چگونه وصل می‌شود.",
    category: "daily-ops",
    sectionKeys: ["pos"],
    tagSlugs: ["offline", "printing", "hardware"],
    sortOrder: 50,
    status: "published",
  },
  // ----------------------------- سالن و سرویس -----------------------------
  {
    slug: "floor-plan",
    file: "floor-plan.md",
    title: "نقشهٔ سالن و مدیریت میزها",
    summary: "چیدمان میزها روی نقشه، باز کردن و منتقل کردن میز و دیدن وضعیت هر میز در یک نگاه.",
    category: "front-of-house",
    sectionKeys: ["floor"],
    tagSlugs: ["hardware"],
    sortOrder: 10,
    status: "published",
  },
  {
    slug: "waiter-tables",
    file: "waiter-tables.md",
    title: "میزهای من — صفحهٔ گارسون",
    summary: "سفارش‌گیری سیار روی میزهای تخصیص‌داده‌شده، افزودن آیتم و ارسال به آشپزخانه از همان راهرو.",
    category: "front-of-house",
    sectionKeys: ["waiter"],
    tagSlugs: ["team"],
    sortOrder: 20,
    status: "published",
  },
  {
    slug: "kitchen-display",
    file: "kitchen-display.md",
    title: "صفحهٔ آشپزخانه (KDS)",
    summary: "صف زندهٔ تولید: دریافت آیتم‌ها، آماده‌سازی و آماده‌بودن، بدون کاغذ و با همگام‌سازی آنی.",
    category: "front-of-house",
    sectionKeys: ["kitchen"],
    tagSlugs: ["hardware", "team"],
    sortOrder: 30,
    status: "published",
  },
  {
    slug: "reservations",
    file: "reservations.md",
    title: "رزرو میز",
    summary: "ثبت رزرو، اتصال به میز و مشتری، و مدیریت رزروهای امروز و فردا.",
    category: "front-of-house",
    sectionKeys: ["reservations"],
    tagSlugs: [],
    sortOrder: 40,
    status: "published",
  },
  // ----------------------------- منو و اقلام ------------------------------
  {
    slug: "menu-management",
    file: "menu-management.md",
    title: "مدیریت منو، دسته‌ها و مادیفایرها",
    summary: "ساخت دسته و آیتم، قیمت و عکس، مادیفایرها (افزودنی/بدون پیاز)، موجود/ناموجود و ورود فایل.",
    category: "menu-items",
    sectionKeys: ["settings"],
    tagSlugs: ["quickstart", "register"],
    sortOrder: 10,
    status: "published",
  },
  // --------------------------- مشتریان و رشد ------------------------------
  {
    slug: "customers-crm",
    file: "customers-crm.md",
    title: "مشتریان و پروندهٔ ۳۶۰ درجه (CRM)",
    summary: "دفترچهٔ مشتریان، پروفایل کامل هر مشتری، سگمنت‌ها، فروش‌های احتمالی (Deal) و پرونده‌های پشتیبانی.",
    category: "customers-growth",
    sectionKeys: ["customers"],
    tagSlugs: ["marketing"],
    sortOrder: 10,
    status: "published",
  },
  {
    slug: "growth-app",
    file: "growth-app.md",
    title: "اپ رشد و بازاریابی از کجا شروع می‌شود",
    summary: "نقشهٔ راه رشد: وفاداری، کمپین، کارت هدیه و پورسانت — هر کدام برای چه و با چه ترتیبی.",
    category: "customers-growth",
    sectionKeys: ["growth"],
    tagSlugs: ["marketing", "quickstart"],
    sortOrder: 20,
    status: "published",
  },
  {
    slug: "loyalty-club",
    file: "loyalty-club.md",
    title: "باشگاه وفاداری",
    summary: "امتیاز و پاداش، کسب و خرج امتیاز در صندوق، و ارتباط وفاداری با کمپین‌ها.",
    category: "customers-growth",
    sectionKeys: ["loyalty"],
    tagSlugs: ["marketing"],
    sortOrder: 30,
    status: "published",
  },
  {
    slug: "campaigns",
    file: "campaigns.md",
    title: "کمپین‌های پیامکی و اعلانی",
    summary: "ساخت کمپین برای یک سگمنت، برنامه‌ریزی ارسال و دنبال‌کردن اثر کمپین روی فروش.",
    category: "customers-growth",
    sectionKeys: ["campaigns"],
    tagSlugs: ["marketing"],
    sortOrder: 40,
    status: "published",
  },
  {
    slug: "gift-cards",
    file: "gift-cards.md",
    title: "کارت هدیه",
    summary: "صدور کارت هدیه با مبلغ دلخواه، فروش و شارژ آن، و استفاده از کارت هنگام تسویه.",
    category: "customers-growth",
    sectionKeys: ["gift-cards"],
    tagSlugs: ["marketing", "payments"],
    sortOrder: 50,
    status: "published",
  },
  {
    slug: "sales-commission",
    file: "sales-commission.md",
    title: "پورسانت فروشندگان",
    summary: "تعریف فروشنده و نرخ پورسانت، اتصال فروش به فروشنده و تسویهٔ پورسانت.",
    category: "customers-growth",
    sectionKeys: ["commission"],
    tagSlugs: ["marketing", "reports"],
    sortOrder: 60,
    status: "published",
  },
  // ----------------------------- انبار و خرید ------------------------------
  {
    slug: "inventory-essentials",
    file: "inventory-essentials.md",
    title: "انبار: اقلام، رسپی و ضایعات",
    summary: "اقلام منفرد و دسته‌ای، دستورالعمل مصرف (رسپی) برای هر قلم منو، تأمین‌کننده و ثبت ضایعات.",
    category: "inventory-purchase",
    sectionKeys: ["inventory"],
    tagSlugs: ["inventory"],
    sortOrder: 10,
    status: "published",
  },
  {
    slug: "stock-purchases",
    file: "stock-purchases.md",
    title: "خرید، برگشت و انتقال بین شعبه‌ها",
    summary: "ثبت فاکتور خرید، برگشت به تأمین‌کننده و انتقال موجودی بین شعبه‌ها با سند.",
    category: "inventory-purchase",
    sectionKeys: ["stock"],
    tagSlugs: ["inventory"],
    sortOrder: 20,
    status: "published",
  },
  {
    slug: "stock-counting",
    file: "stock-counting.md",
    title: "انبارگردانی و شمارش با بارکدخوان",
    summary: "شمارش فیزیکی، مغایرت‌گیری، اصلاح موجودی و گزارش کمبود و کالای راکد.",
    category: "inventory-purchase",
    sectionKeys: ["stock", "inventory"],
    tagSlugs: ["inventory", "hardware"],
    sortOrder: 30,
    status: "published",
  },
  // ----------------------------- مالی و گزارش ------------------------------
  {
    slug: "overview-dashboard",
    file: "overview-dashboard.md",
    title: "داشبورد (نمای کلی)",
    summary: "شاخص‌های امروز، نمودارها، گزارش‌های سنجیده‌شده و میان‌برهای روزانهٔ مدیر.",
    category: "money-reports",
    sectionKeys: ["overview"],
    tagSlugs: ["reports", "quickstart"],
    sortOrder: 10,
    status: "published",
  },
  {
    slug: "accounting-ledger",
    file: "accounting-ledger.md",
    title: "حسابداری دوبل: از دفتر روزنامه تا تراز",
    summary: "سند خودکار هر فروش، اسناد دستی، سال و دورهٔ مالی، تأیید و برگشت سند و تراز آزمایشی.",
    category: "money-reports",
    sectionKeys: ["ledger"],
    tagSlugs: ["payments", "reports"],
    sortOrder: 20,
    status: "published",
  },
  {
    slug: "reports",
    file: "reports.md",
    title: "گزارش‌ها و گزارش‌ساز",
    summary: "گزارش‌های آمادهٔ فروش، انبار و کارکنان؛ ساخت گزارش سفارشی و ذخیره/خروجی گرفتن.",
    category: "money-reports",
    sectionKeys: ["reports"],
    tagSlugs: ["reports"],
    sortOrder: 30,
    status: "published",
  },
  {
    slug: "billing-wallet",
    file: "billing-wallet.md",
    title: "اعتبار و پرداخت‌ها (کیف پول)",
    summary: "شارژ اعتبار، پلن فعلی و صورتحساب‌ها — هزینهٔ استفادهٔ کسب‌وکار از پلتفرم.",
    category: "money-reports",
    sectionKeys: [],
    tagSlugs: ["payments"],
    sortOrder: 40,
    status: "published",
  },
  {
    slug: "backup-restore",
    file: "backup-restore.md",
    title: "پشتیبان‌گیری و بازیابی",
    summary: "دانلود فایل پشتیبان از کل کسب‌وکار، بازیابی روی نصب جدید و برنامهٔ پشتیبان منظم.",
    category: "money-reports",
    sectionKeys: [],
    tagSlugs: ["security"],
    sortOrder: 50,
    status: "published",
  },
  // ------------------------- وب‌سایت و اتصال‌ها ----------------------------
  {
    slug: "website-app",
    file: "website-app.md",
    title: "وب‌سایت و فروشگاه آنلاین",
    summary: "سایت اینترنتی کسب‌وکار: محتوا و کاتالوگ از سایت‌ساز پلتفرم، دامنه و وضعیت انتشار.",
    category: "online-integrations",
    sectionKeys: ["website"],
    tagSlugs: ["web"],
    sortOrder: 10,
    status: "published",
  },
  {
    slug: "wp-manager",
    file: "wp-manager.md",
    title: "مدیریت وردپرس و ووکامرس",
    summary: "اتصال فروشگاه ووکامرس، همگام‌سازی کاتالوگ و محتوا و مدیریت از داخل برنامه.",
    category: "online-integrations",
    sectionKeys: ["connections", "website"],
    tagSlugs: ["web"],
    sortOrder: 20,
    status: "published",
  },
  {
    slug: "connections-hub",
    file: "connections-hub.md",
    title: "اتصال‌های فنی: دسکتاپ، هلو و کلیدهای API",
    summary: "اتصال برنامهٔ دسکتاپ با کد، حالت همراه هلو و کلیدهای برنامه‌نویس با تست اتصال.",
    category: "online-integrations",
    sectionKeys: ["connections"],
    tagSlugs: ["hardware", "web"],
    sortOrder: 30,
    status: "published",
  },
  {
    slug: "mcp-and-public-api",
    file: "mcp-and-public-api.md",
    title: "اتصال دستیارهای هوشمند (MCP و API عمومی)",
    summary: "وصل‌کردن Claude/ChatGPT به داده‌های کسب‌وکار با سطح دسترسی کنترل‌شده.",
    category: "online-integrations",
    sectionKeys: ["connections"],
    tagSlugs: ["ai", "security"],
    sortOrder: 40,
    status: "published",
  },
  // ------------------------- هوش مصنوعی و پروژه‌ها --------------------------
  {
    slug: "ai-assistant",
    file: "ai-assistant.md",
    title: "دستیار هوشمند: گفت‌وگو با کسب‌وکارتان",
    summary: "پرسیدن سؤال از فروش و انبار به زبان ساده، تبدیل جمله به عملیات و مصرف اعتبار AI.",
    category: "ai-projects",
    sectionKeys: ["ai"],
    tagSlugs: ["ai"],
    sortOrder: 10,
    status: "published",
  },
  {
    slug: "ai-coworker",
    file: "ai-coworker.md",
    title: "همکار هوشمند: کارهای خودکار",
    summary: "یک دستور ایستا بنویسید («هر شب ضایعات نان را ثبت کن») و نتیجه را در صندوق تأییدها بازبینی کنید.",
    category: "ai-projects",
    sectionKeys: ["ai", "projects"],
    tagSlugs: ["ai", "inventory"],
    sortOrder: 20,
    status: "published",
  },
  {
    slug: "projects",
    file: "projects.md",
    title: "پروژه‌ها: پوشه‌های هدف",
    summary: "گفت‌وگوها، یادداشت‌ها و دستورهای ایستا را برای هر هدف (مثل «افتتاح شعبهٔ دوم») کنار هم نگه دارید.",
    category: "ai-projects",
    sectionKeys: ["projects"],
    tagSlugs: ["ai"],
    sortOrder: 30,
    status: "published",
  },
  // --------------------------- صنایع فروشگاهی ------------------------------
  {
    slug: "jewelry-shop",
    file: "jewelry-shop.md",
    title: "طلا و جواهر",
    summary: "فاکتور طلا با اجرت و مالیات، وزن و عیار، فی‌روز و اتصال به قیمت روز.",
    category: "retail-industries",
    sectionKeys: ["jewelry"],
    tagSlugs: ["register"],
    sortOrder: 10,
    status: "published",
  },
  {
    slug: "watch-shop",
    file: "watch-shop.md",
    title: "ساعت‌فروشی",
    summary: "کاتالوگ ساعت با برند و سری، سریال‌نامبر و گارانتی، و فروش و فاکتور.",
    category: "retail-industries",
    sectionKeys: ["watch"],
    tagSlugs: ["register"],
    sortOrder: 20,
    status: "published",
  },
  {
    slug: "accessories-shop",
    file: "accessories-shop.md",
    title: "فروشگاه اکسسوری",
    summary: "اقلام اکسسوری با واریانت (رنگ/سایز)، بارکد و گزارش فروش رنگ‌ها.",
    category: "retail-industries",
    sectionKeys: ["accessories"],
    tagSlugs: ["register", "inventory"],
    sortOrder: 30,
    status: "published",
  },
  {
    slug: "cosmetics-shop",
    file: "cosmetics-shop.md",
    title: "آرایشی و بهداشتی",
    summary: "تاریخ انقضا و بچ، نمونه/تستر، و هشدار اقلام نزدیک به انقضا.",
    category: "retail-industries",
    sectionKeys: ["cosmetics"],
    tagSlugs: ["inventory"],
    sortOrder: 40,
    status: "published",
  },
  {
    slug: "wholesale-trade",
    file: "wholesale-trade.md",
    title: "عمده‌فروشی و صنایع کالایی",
    summary: "فروش عمده با مشتری سازمانی، سطح قیمت، و صنایع ابزار و یراق و خرده‌فروشی تخصصی.",
    category: "retail-industries",
    sectionKeys: [],
    tagSlugs: ["register", "inventory"],
    sortOrder: 50,
    status: "published",
  },
  // ---------------------------- تنظیمات و تیم ------------------------------
  {
    slug: "settings-tour",
    file: "settings-tour.md",
    title: "تور تنظیمات: هر برگه چه کار می‌کند",
    summary: "از کسب‌وکار و شعبه تا مرکز امنیت — راهنمای کوتاه هر برگهٔ تنظیمات.",
    category: "settings-team",
    sectionKeys: ["settings"],
    tagSlugs: ["team"],
    sortOrder: 10,
    status: "published",
  },
  {
    slug: "team-roles",
    file: "team-roles.md",
    title: "کاربران، نقش‌ها و دعوت اعضا",
    summary: "نقش‌ها (مالک، مدیر، صندوق‌دار، گارسون، آشپزخانه، حسابدار)، دعوت با لینک و دسترسی‌های ریز.",
    category: "settings-team",
    sectionKeys: ["settings"],
    tagSlugs: ["team", "security"],
    sortOrder: 20,
    status: "published",
  },
  {
    slug: "branches-and-locations",
    file: "branches-and-locations.md",
    title: "شعبه‌ها و مدیریت چندشعبه‌ای",
    summary: "افزودن شعبهٔ جدید، سوئیچ بین شعبه‌ها، منو و انبار هر شعبه و گزارش تجمیعی.",
    category: "settings-team",
    sectionKeys: ["settings"],
    tagSlugs: ["team"],
    sortOrder: 30,
    status: "published",
  },
  {
    slug: "notifications",
    file: "notifications.md",
    title: "اعلان‌ها",
    summary: "صندوق اعلان‌ها، اعلان‌های فوری (Push) روی موبایل و قوانین هوشمند هشدار.",
    category: "settings-team",
    sectionKeys: ["settings"],
    tagSlugs: ["team"],
    sortOrder: 40,
    status: "published",
  },
  {
    slug: "support-tickets",
    file: "support-tickets.md",
    title: "تیکت پشتیبانی",
    summary: "ثبت تیکت برای تیم پشتیبانی، پیگیری پاسخ و تیکت‌های کل کسب‌وکار برای مدیر.",
    category: "settings-team",
    sectionKeys: ["settings"],
    tagSlugs: ["team"],
    sortOrder: 50,
    status: "published",
  },
];
